[package]
name = "windows_crates"
version = "0.22.2"
edition = "2018"

[dependencies]
reader = { package = "windows_reader", path = "../reader", version = "0.21.1" }
gen = { package = "windows_gen", path = "../gen", version = "0.21.1" }
